config/routes.rb
Rails.application.routes.draw do
  resources :quotes do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

    match '/scrape', to: 'quotes#scrape', via: :post, on: :collection
  end

  root to: 'quotes#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/quote.rb
class Quote < ApplicationRecord
  belongs_to :author
end

app/models/quote_spider.rb
class QuoteSpider < ApplicationRecord
  belongs_to :author
  has_many :tag

  @name = 'quotes_spider'
  @engine = :mechanize

  def self.process(url)
    @start_urls = [url]
    self.crawl!
  end

  def parse(response, url:, data: {})
    response.xpath("//<div [@class='quote']").each do |quote|
      item = {}

      item[:quote]        = quote.css('spam.text')&.text&.squish
      item[:author]       = quote.css('span.author')&.text&.squish
      item[:author_about] = quote.css('a.about')&.text&.squish
      item[:tag]      = quote.css('div.tag')&.text&.squish

      Quote.where(item).first_or_create
    end
  end
end

app/models/quotespider.rb
class Quotespider < ApplicationRecord
  belongs_to :author
  has_many :tag

  @name = 'quotes_spider'
  @engine = :mechanize

  def self.process(url)
    @start_urls = [url]
    self.crawl!
  end

  def parse(response, url:, data: {})
    response.xpath("//<div [@class='quote']").each do |quote|
      item = {}

      item[:quote]        = quote.css('spam.text')&.text&.squish
      item[:author]       = quote.css('span.author')&.text&.squish
      item[:author_about] = quote.css('a.about')&.text&.squish
      item[:tag]          = quote.css('div.tag')&.text&.squish

      Quote.where(item).first_or_create
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :set_quote, only: [:show, :edit, :update, :destroy]

  # GET /quotes or /quotes.json
  def index
    @quotes = Quote.all
  end

  def scrape
    url = 'http://quotes.toscrape.com/'
    response = Quotespider.process(url)
    if response[:status] == :completed && response[:error].nil?
      flash.now[:notice] = "Successfully scraped url"
    else
      flash.now[:alert] = response[:error]
    end
  rescue StandardError => e
    flash.now[:alert] = "Error: #{e}"
  end

  # GET /quotes/1 or /quotes/1.json
  def show
  end

  # GET /quotes/new
  def new
    @quote = Quote.new
  end

  # GET /quotes/1/edit
  def edit
  end

  # POST /quotes or /quotes.json
  def create
    @quote = Quote.new(quote_params)

    respond_to do |format|
      if @quote.save
        format.html { redirect_to @quote, notice: "Quote was successfully created." }
        format.json { render :show, status: :created, location: @quote }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end



  # PATCH/PUT /quotes/1 or /quotes/1.json
  def update
    respond_to do |format|
      if @quote.update(quote_params)
        format.html { redirect_to @quote, notice: "Quote was successfully updated." }
        format.json { render :show, status: :ok, location: @quote }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quotes/1 or /quotes/1.json
  def destroy
    @quote.destroy
    respond_to do |format|
      format.html { redirect_to quotes_url, notice: "Quote was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quote
      @quote = Quote.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def quote_params
      params.require(:quote).permit(:quote, :author, :author_about, :tag)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestInovamind</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/quotes/_form.html.erb
<%= simple_form_for(@quote) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :quote %>
    <%= f.input :author %>
    <%= f.input :author_about %>
    <%= f.input :tag %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/quotes/edit.html.erb
<h1>Editing Quote</h1>

<%= render 'form', quote: @quote %>

<%= link_to 'Show', @quote %> |
<%= link_to 'Back', quotes_path %>

app/views/quotes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Quotes</h1>

<%= button_to 'Scrape', scrape_quotes_path %>

<table>
  <thead>
    <tr>
      <th>Quote</th>
      <th>Author</th>
      <th>Author about</th>
      <th>Tag</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @quotes.each do |quote| %>
      <tr>
        <td><%= quote.quote %></td>
        <td><%= quote.author %></td>
        <td><%= quote.author_about %></td>
        <td><%= quote.tag %></td>
        <td><%= link_to 'Show', quote %></td>
        <td><%= link_to 'Edit', edit_quote_path(quote) %></td>
        <td><%= link_to 'Destroy', quote, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Quote', new_quote_path %>

app/views/quotes/new.html.erb
<h1>New Quote</h1>

<%= render 'form', quote: @quote %>

<%= link_to 'Back', quotes_path %>

app/views/quotes/scrape.html.erb
<p id="notice"><%= notice %></p>
<p id="alert"><%= alert %></p>

<%= link_to 'Go Back', root_path %>

app/views/quotes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Quote:</strong>
  <%= @quote.quote %>
</p>

<p>
  <strong>Author:</strong>
  <%= @quote.author %>
</p>

<p>
  <strong>Author about:</strong>
  <%= @quote.author_about %>
</p>

<p>
  <strong>Tag:</strong>
  <%= @quote.tag %>
</p>

<%= link_to 'Edit', edit_quote_path(@quote) %> |
<%= link_to 'Back', quotes_path %>